source "https://rubygems.org"
gem "rails", "4.2.6"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bootstrap-sass", "3.2.0.0"
gem "bootstrap-will_paginate"
gem "font-awesome-rails"
gem "config"
gem "devise"
gem "will_paginate"
gem "kaminari"
gem "bootstrap-kaminari-views"
gem "omniauth"
gem "omniauth-google-oauth2"
gem "json"
gem "omniauth-facebook"
gem "figaro"
gem "omniauth-twitter"
gem "cancancan", "~> 1.10"
gem "ransack"
gem "simple_form"
gem "ckeditor"
gem "carrierwave", "0.10.0"
gem "mini_magick", "3.8.0"
gem "fog", "1.36.0"
gem "chatwork"
gem "chartkick", "~> 1.2.4"
gem "groupdate", "~> 2.1.1"
gem "active_median", "~> 0.1.0"
gem "social-share-button"
gem "public_activity"
group :development, :test do
  gem "byebug"
end
group :development do
  gem "web-console", "~> 2.0"
  gem "spring"
  gem "sqlite3"
  gem "seed_dump"
end
group :production do
  gem "pg"
  gem "non-stupid-digest-assets", "~> 1.0.4"
end
