source "https://rubygems.org"
gem "rails", "4.2.6"
gem "sqlite3"
gem "sass-rails", "~> 5.0"
gem "uglifier", ">= 1.3.0"
gem "coffee-rails", "~> 4.1.0"
gem "jquery-rails"
gem "turbolinks"
gem "jbuilder", "~> 2.0"
gem "sdoc", "~> 0.4.0", group: :doc
gem "bootstrap-sass", "3.2.0.0"
gem "bootstrap-will_paginate"
gem "font-awesome-rails"
gem "config"
gem "devise"
gem "cancancan", "~> 1.10"
gem "will_paginate"
gem "bootstrap-will_paginate"
gem "kaminari"
gem "ransack"
gem "bootstrap-kaminari-views"
gem "simple_form"
gem "ckeditor"
gem "carrierwave", "0.10.0"
gem "mini_magick", "3.8.0"
gem "fog", "1.36.0"
gem "public_activity"
group :development, :test do
  gem "byebug"
end
group :development do
  gem "web-console", "~> 2.0"
  gem "spring"
end
