telephone: "09020049841"
address: "18-floor, Landmark72 Tower, Ha Noi, Viet Nam"
card_page: 5
show_limit:
  show_5: 5
  show_10: 10
  show_15: 15
  show_20: 20
  show_30: 30
  show_50: 50
product_take: 5
